(ns ai.obney.grain.datastar.core
  "Server-side Datastar integration for Grain's CQRS architecture.

   Connects the event-sourced command/query pipeline to the browser via SSE:

     Command → Events → Pubsub → SSE event loops → Re-render query → Patch DOM

   ## Three streaming modes

   1. **Event-driven** (primary) — SSE stays open; re-renders when domain events
      fire via pubsub subscription. Enabled when the query declares
      `:grain/read-models` and `:event-pubsub` is in the context.

   2. **Polling** — Re-renders on a timer (`:datastar/fps`). Fallback when no
      pubsub is available.

   3. **One-shot** — Renders once and closes (`:datastar/fps 0`).

   ## Signal flow

   Datastar signals flow in two directions:

   - **Server → Client**: `datastar-patch-signals` SSE events push signal
     changes (e.g., toast messages, field errors) to the browser.

   - **Client → Server**: Datastar sends signals via `@get` (query params) or
     `@post` (JSON body). The `parse-datastar-signals` interceptor normalizes
     both into `:query-params` for the query handler.

   ## Connection reuse via active-stream-contexts

   When the user changes signals (e.g., filters, search), both `@get` and
   `@post` requests check for an existing connection by `[user-id, query-name,
   nonce]` in the `active-stream-contexts` registry. If found, the server
   updates the context atom with the new signals, triggers a re-render on the
   existing SSE via `signal-ch`, and returns an empty SSE that closes
   immediately. GET reuse requires a nonce (generated by the shim page); POST
   always attempts reuse for backward compatibility.

   ## Route generation

   `routes` scans the query registry for entries with `:datastar/path` metadata
   and auto-generates three Pedestal routes per query:
     1. **Shim** (GET `/path`) — HTML shell that boots Datastar JS
     2. **Stream GET** (`/path/__stream`) — SSE (reuses existing session if nonce matches)
     3. **Stream POST** (`/path/__stream`) — Signal updates on existing SSE

   ## Auth and gate interceptors

   `routes` accepts a `defaults` map with:
   - `:datastar/auth-redirect` — auto-generates redirect interceptors from each
     query's `:authorized?` predicate. Public queries are skipped.
   - Queries may declare `:datastar/gate {:check fn :redirect path}` for
     context-dependent guards. The adapter builds the interceptor at route time,
     merging the grain context with per-request auth claims.

   See `ai.obney.grain.datastar.interface` for the public API."
  (:require [hiccup2.core :as h]
            [clojure.data.json :as json]
            [clojure.set :as set]
            [clojure.core.async :as async]
            [clojure.core.async.impl.protocols :as async-protocols]
            [clojure.string :as string]
            [io.pedestal.http.sse :as sse]
            [ai.obney.grain.query-processor.interface :as qp]
            [ai.obney.grain.command-processor-v2.interface :as cp]
            [ai.obney.grain.pubsub.interface :as pubsub]
            [ai.obney.grain.read-model-processor-v2.interface :as rmp]
            [ai.obney.grain.time.interface :as time]
            [ai.obney.grain.anomalies.interface :refer [anomaly?]]
            [cognitect.anomalies :as anom]
            [malli.core :as mc]
            [malli.transform :as mt]
            [com.brunobonacci.mulog :as u]))

;; --------------- ;;
;; HTML Rendering  ;;
;; --------------- ;;

(defn render-html [hiccup]
  (str (h/html hiccup)))

;; ---------------------- ;;
;; SSE Event Formatters   ;;
;; ---------------------- ;;

(defn patch-elements [html opts]
  (let [{:keys [selector mode]} opts
        html-lines (string/split-lines html)
        element-lines (mapv #(str "elements " %) html-lines)
        data-lines (cond-> []
                     selector (conj (str "selector " selector))
                     (and mode (not= mode :outer)) (conj (str "mode " (name mode)))
                     true (into element-lines))]
    {:name "datastar-patch-elements"
     :data (string/join "\n" data-lines)}))

(defn patch-signals [signals opts]
  (let [{:keys [only-if-missing]} opts
        json-str (json/write-str signals)
        data-lines (cond-> []
                     only-if-missing (conj "onlyIfMissing true")
                     true (conj (str "signals " json-str)))]
    {:name "datastar-patch-signals"
     :data (string/join "\n" data-lines)}))

;; -------------------- ;;
;; Malli JSON Coercion  ;;
;; -------------------- ;;

(defn- decode-json-query
  "Coerces query params from string values into proper EDN types
   using the query's registered Malli schema + json-transformer."
  [raw-query]
  (let [query-name (:query/name raw-query)
        query-schema (try (when query-name (mc/schema query-name))
                          (catch Exception e
                            (u/log ::missing-query-schema
                                   :query-name query-name
                                   :error (.getMessage e))
                            nil))
        decoded (if query-schema
                  (mc/decode query-schema raw-query (mt/json-transformer))
                  raw-query)]
    (assoc decoded
           :query/name query-name
           :query/id (random-uuid)
           :query/timestamp (time/now))))

(defn- parse-signals [request]
  (when-let [body (:body request)]
    (let [body-str (if (string? body) body (slurp body))]
      (when (seq body-str)
        (json/read-str body-str :key-fn keyword)))))

(defn- stringify-signal-values
  "Coerce signal values to strings to match GET query-param semantics.
   Skips maps and collections (e.g. fieldErrors) — only primitives are stringified."
  [signals]
  (reduce-kv (fn [m k v]
               (assoc m k (cond
                            (string? v) v
                            (nil? v) ""
                            (or (map? v) (sequential? v)) v
                            :else (str v))))
             {} signals))

(def parse-datastar-signals
  "Interceptor that extracts Datastar signals from the `datastar` query param (GET)
   or JSON body (POST) and merges them into the request's :query-params map.
   Auto-included by `query->route-pair` on all generated routes.

   POST body formats:
   - Wrapped:  {\"datastar\": {\"key\": \"val\"}}  (older Datastar convention)
   - Flat:     {\"key\": \"val\"}                   (Datastar RC.7+)

   Both GET and POST paths merge native JSON types (integers stay integers)."
  {:name ::parse-datastar-signals
   :enter
   (fn [ctx]
     (let [ds-param (or (get-in ctx [:request :query-params :datastar])
                        (get-in ctx [:request :query-params "datastar"]))
           ds-body (when (and (nil? ds-param)
                              (= :post (get-in ctx [:request :request-method])))
                     (try
                       (when-let [body (get-in ctx [:request :body])]
                         (let [body-str (if (string? body) body (slurp body))]
                           (when (seq body-str)
                             (let [parsed (json/read-str body-str :key-fn keyword)]
                               ;; Unwrap {:datastar {...}} if present, otherwise use flat signals
                               (or (:datastar parsed) parsed)))))
                       (catch Exception _ nil)))]
       (cond
         ds-param
         (try
           (let [signals (json/read-str ds-param :key-fn keyword)]
             (update-in ctx [:request :query-params] merge signals))
           (catch Exception _ ctx))

         ds-body
         (update-in ctx [:request :query-params] merge ds-body)

         :else ctx)))})

(defn- decode-json-command
  "Coerces a raw JSON-parsed command map into proper EDN types using
   the command's registered Malli schema + json-transformer."
  [raw-command]
  (let [command-name (let [n (:command/name raw-command)]
                       (cond
                         (keyword? n) n
                         (string? n)  (keyword (cond-> n (string/starts-with? n ":") (subs 1)))
                         :else n))
        raw-command (assoc raw-command :command/name command-name)
        command-schema (try (when command-name (mc/schema command-name))
                            (catch Exception _ nil))
        decoded (if command-schema
                  (mc/decode command-schema raw-command
                            (mt/transformer (mt/json-transformer)
                                            (mt/strip-extra-keys-transformer)))
                  raw-command)]
    (assoc decoded
           :command/name command-name
           :command/id (random-uuid)
           :command/timestamp (time/now))))

;; -------------------------------- ;;
;; Active Stream Context Registry   ;;
;; -------------------------------- ;;

;; Registry of active event-driven SSE connections.
;; Key:   [user-id query-name nonce] — nonce is a per-page-load UUID so
;;        multiple tabs viewing the same query get independent streams.
;; Value: {:context-atom atom, :signal-ch channel, :event-ch channel}
;;
;; Lifecycle: entries are added in `stream-view-loop-events` when a GET
;; opens a new SSE, and removed in its `finally` block when the stream
;; closes (browser navigates away or server shuts down).
;;
;; Purpose: `update-or-start-stream-events` looks up an existing entry
;; on @post to push new signals into the persistent SSE instead of
;; opening a duplicate connection.
(def ^:private active-stream-contexts (atom {}))

;; --------------- ;;
;; Query Polling   ;;
;; --------------- ;;

(defn poll-and-render
  "Single poll cycle. Returns {:event sse-event :result query-data} if changed, nil if unchanged."
  [query-context prev-result]
  (let [query-registry (or (:query-registry query-context) @qp/query-registry*)
        query-name (get-in query-context [:query :query/name])
        authorized? (get-in query-registry [query-name :authorized?])]
    (if (and authorized? (true? (authorized? query-context)))
      (let [result (qp/process-query query-context)
            query-data (when-not (anomaly? result) (:query/result result))]
        (when (not= query-data prev-result)
          (when-let [hiccup (:datastar/hiccup result)]
            {:event (patch-elements (render-html hiccup) {})
             :result query-data})))
      (do
        (when-not authorized?
          (u/log ::missing-authorized-predicate :query-name query-name))
        {:event (patch-signals {:error "Unauthorized"} {})
         :result prev-result
         :stop? true}))))

;; ------------------------ ;;
;; Interceptor Factories    ;;
;; ------------------------ ;;

(defn- extract-query-from-request
  "Builds the raw query map from a request.
   Reads :query-params (populated by interceptors for both GET and POST)
   and :path-params."
  [request query-name]
  (merge {:query/name query-name}
         (:query-params request)
         (:path-params request)))

(defn- stream-view-loop
  "Polling loop for stream-view. Runs on SSE thread.
   When interval-ms is nil (fps 0), renders once and closes."
  [event-ch sse-ctx context query-name interval-ms additional-context]
  (let [request (:request sse-ctx)
        raw-query (extract-query-from-request request query-name)
        decoded-query (decode-json-query raw-query)
        query-context (merge context additional-context {:query decoded-query})]
    (try
      (if-not interval-ms
        ;; One-shot mode: render once and close
        (let [poll-result (poll-and-render query-context nil)]
          (when poll-result
            (async/>!! event-ch (:event poll-result))))
        ;; Polling mode: loop until channel closes or client disconnects
        (loop [prev-result nil]
          (let [start-time (System/currentTimeMillis)
                poll-result (poll-and-render query-context prev-result)]
            (cond
              (:stop? poll-result)
              (async/>!! event-ch (:event poll-result))

              poll-result
              (let [sent? (async/alt!!
                            [[event-ch (:event poll-result)]] true
                            :default false)]
                (when sent?
                  (let [elapsed (- (System/currentTimeMillis) start-time)
                        sleep-ms (max 0 (- interval-ms elapsed))]
                    (when (pos? sleep-ms) (Thread/sleep sleep-ms))
                    (recur (:result poll-result)))))

              :else
              (when-not (async-protocols/closed? event-ch)
                (let [elapsed (- (System/currentTimeMillis) start-time)
                      sleep-ms (max 0 (- interval-ms elapsed))]
                  (when (pos? sleep-ms) (Thread/sleep sleep-ms))
                  (recur prev-result)))))))
      (catch Exception e (u/log ::stream-view-error :error e))
      (finally (async/close! event-ch)))))

(defn- stream-view-enter
  "Enter fn for stream-view interceptor (polling mode)."
  [context query-name interval-ms heartbeat-delay pedestal-context]
  (let [additional-context (:grain/additional-context pedestal-context)]
    (sse/start-stream
      (fn [event-ch sse-ctx]
        (stream-view-loop event-ch sse-ctx context query-name interval-ms additional-context))
      pedestal-context
      heartbeat-delay)))

;; ----------------------------- ;;
;; Event-Driven Streaming        ;;
;; ----------------------------- ;;

(defn- resolve-events
  "Resolves :grain/read-models map to a union of their :events sets.
   read-models is a map of {rm-name version, ...}.
   The version is declarative — multiple versions can co-exist."
  [read-models]
  (let [registry @rmp/read-model-registry*]
    (into #{}
          (mapcat (fn [[rm-name _version]]
                    (:events (get registry rm-name))))
          read-models)))

(defn- resolve-event-tags
  "Resolves a {:tag-key :query-key-or-path} map against query-context into
   a predicate (fn [event] -> boolean) suitable for a channel transducer.
   Bare keyword values resolve from [:query k]; vectors are full get-in paths."
  [event-tags query-context]
  (let [resolved (into #{}
                       (map (fn [[tag-key path]]
                              [tag-key (if (vector? path)
                                         (get-in query-context path)
                                         (get-in query-context [:query path]))]))
                       event-tags)]
    (fn [event]
      (set/subset? resolved (:event/tags event)))))

(defn- subscribe-to-events
  "Creates a sliding-buffer channel and subscribes it to each event type via pubsub.
   When event-filter-fn is provided, applies it as a transducer on the channel.
   Returns the subscription channel."
  [event-pubsub event-types event-filter-fn]
  (let [buf (async/sliding-buffer 64)
        sub-chan (if event-filter-fn
                  (async/chan buf (filter event-filter-fn))
                  (async/chan buf))]
    (doseq [event-type event-types]
      (pubsub/sub event-pubsub {:topic event-type :sub-chan sub-chan}))
    sub-chan))

(defn- drain-channel
  "Non-blocking drain of all buffered messages on ch. Returns count drained."
  [ch]
  (loop [n 0]
    (if-let [_ (async/poll! ch)]
      (recur (inc n))
      n)))

(defn- stream-view-loop-events
  "Event-driven loop for stream-view. Subscribes to event types, re-renders on events.
   Sub-chan is created BEFORE initial render to avoid missing events.
   Query context is stored in an atom so @post can update signals mid-stream."
  [event-ch sse-ctx context query-name event-pubsub event-types debounce-ms additional-context event-tags]
  (let [request (:request sse-ctx)
        raw-query (extract-query-from-request request query-name)
        nonce (or (:dsNonce raw-query) (get raw-query "dsNonce"))
        decoded-query (decode-json-query (dissoc raw-query :dsNonce "dsNonce"))
        initial-context (merge context additional-context {:query decoded-query})
        context-atom (atom initial-context)
        signal-ch (async/chan (async/sliding-buffer 1))
        user-id (get-in additional-context [:auth-claims :user-id])
        session-key [user-id query-name nonce]
        _ (swap! active-stream-contexts assoc session-key
                 {:context-atom context-atom :signal-ch signal-ch :event-ch event-ch})
        event-filter-fn (when event-tags
                          (resolve-event-tags event-tags @context-atom))
        sub-chan (subscribe-to-events event-pubsub event-types event-filter-fn)]
    (try
      ;; Initial render
      (let [initial (poll-and-render @context-atom nil)]
        (when initial
          (async/>!! event-ch (:event initial)))
        (when (:stop? initial)
          (throw (ex-info "stop" {:stop true})))
        ;; Event loop — listens to domain events AND signal updates
        (loop [prev-result (:result initial)]
          (let [[val _port] (async/alts!! [sub-chan signal-ch (async/timeout 30000)])]
            (cond
              ;; Channel closed (pubsub shutting down or signal-ch closed)
              (and (nil? val) (or (async-protocols/closed? sub-chan)
                                  (async-protocols/closed? signal-ch)))
              nil

              ;; Timeout — liveness check
              (nil? val)
              (if (async-protocols/closed? event-ch)
                nil
                (recur prev-result))

              ;; Event or signal update received. Debounce then drain BOTH channels
              ;; before re-rendering. Draining both is a correctness requirement, not
              ;; just a performance optimization: if a domain event and a signal update
              ;; arrive near-simultaneously, we must apply the signal change before
              ;; re-rendering — otherwise the query runs with stale signals and the
              ;; user sees a flash of old state before the signal update triggers
              ;; another render cycle.
              :else
              (do
                (when (pos? debounce-ms) (Thread/sleep (long debounce-ms)))
                (drain-channel sub-chan)
                (drain-channel signal-ch)
                (let [poll-result (poll-and-render @context-atom prev-result)]
                  (cond
                    (:stop? poll-result)
                    (async/>!! event-ch (:event poll-result))

                    poll-result
                    (let [sent? (async/alt!!
                                  [[event-ch (:event poll-result)]] true
                                  :default false)]
                      (if sent?
                        (recur (:result poll-result))
                        nil))

                    :else
                    (recur prev-result))))))))
      (catch Exception e
        (when-not (= "stop" (.getMessage e))
          (u/log ::stream-view-events-error :error e)))
      (finally
        (swap! active-stream-contexts dissoc session-key)
        (async/close! signal-ch)
        (async/close! sub-chan)
        (async/close! event-ch)))))

(defn- stream-view-enter-events
  "Enter fn for stream-view interceptor (event-driven mode)."
  [context query-name event-pubsub event-types debounce-ms heartbeat-delay event-tags pedestal-context]
  (let [additional-context (:grain/additional-context pedestal-context)]
    (sse/start-stream
      (fn [event-ch sse-ctx]
        (stream-view-loop-events event-ch sse-ctx context query-name
                                 event-pubsub event-types debounce-ms additional-context event-tags))
      pedestal-context
      heartbeat-delay)))

(defn- update-or-start-stream-events
  "If an active event-driven SSE exists for this user+query+nonce, update its
   context atom with new signals and trigger a re-render via signal-ch, then
   return an empty SSE that closes immediately. Otherwise start a new SSE.
   Works for both GET and POST — enables signal updates without reconnecting.
   For GET requests, session reuse requires a nonce (dsNonce) to avoid
   accidental collisions; POST always attempts reuse for backward compatibility."
  [context query-name event-pubsub event-types debounce-ms heartbeat-delay event-tags pedestal-context]
  (let [additional-context (:grain/additional-context pedestal-context)
        request (:request pedestal-context)
        raw-query (extract-query-from-request request query-name)
        nonce (or (:dsNonce raw-query) (get raw-query "dsNonce"))
        is-post? (= :post (:request-method request))
        user-id (get-in additional-context [:auth-claims :user-id])
        session-key [user-id query-name nonce]
        ;; For GET, only attempt reuse when a nonce is present — nonce is the
        ;; explicit opt-in for session reuse (generated by shim-page per page load).
        ;; Without nonce, GET always starts fresh to avoid accidental collisions.
        ;; POST always attempts reuse for backward compatibility.
        existing (when (or is-post? nonce)
                   (get @active-stream-contexts session-key))
        ;; Only use existing if both signal-ch and event-ch are still open.
        ;; event-ch closes when the browser disconnects (page navigation);
        ;; signal-ch closes when the event loop's finally block runs.
        existing (when (and existing
                            (not (async-protocols/closed? (:signal-ch existing)))
                            (not (async-protocols/closed? (:event-ch existing))))
                   existing)]
    (if existing
      ;; Update existing SSE's context with new signals (from :query-params, already parsed by interceptor)
      (let [new-decoded (decode-json-query (dissoc raw-query :dsNonce "dsNonce"))
            {:keys [context-atom signal-ch]} existing]
        (swap! context-atom assoc :query new-decoded)
        (async/put! signal-ch :signal-update)
        ;; Return empty SSE — close immediately. The real re-render happens
        ;; on the existing SSE via signal-ch.
        (sse/start-stream (fn [ch _] (async/close! ch)) pedestal-context heartbeat-delay))
      ;; No existing SSE (or stale) — clean up stale entry and start fresh.
      ;; Close old signal-ch so the orphaned event loop exits cleanly.
      (do
        (when (or is-post? nonce)
          (when-let [stale (get @active-stream-contexts session-key)]
            (async/close! (:signal-ch stale))))
        (stream-view-enter-events context query-name event-pubsub event-types
                                  debounce-ms heartbeat-delay event-tags pedestal-context)))))

(defn stream-view
  "Interceptor factory. Streams :datastar/hiccup via SSE.

   Modes:
   - Event-driven: when :event-types is non-empty AND :event-pubsub is in context,
     re-renders only when relevant events fire. Both GET and POST requests check
     for an existing SSE (by user+query+nonce) and reuse it for signal updates
     without reconnecting. If no existing SSE is found, a fresh one is started.
   - Polling: when :fps is positive, polls at the given FPS.
   - One-shot: when :fps is 0 or nil, renders once and closes."
  [context query-name opts]
  (let [{:keys [fps heartbeat-delay event-types debounce-ms event-tags]
         :or {fps 30 heartbeat-delay 10 debounce-ms 50}} opts
        event-pubsub (:event-pubsub context)]
    (if (and (seq event-types) event-pubsub)
      ;; Event-driven mode — both GET and POST check for existing SSE first
      {:name (keyword "ai.obney.grain.datastar.core" (str "stream-" (name query-name)))
       :enter (fn [pedestal-context]
                (update-or-start-stream-events context query-name event-pubsub event-types
                                                debounce-ms heartbeat-delay event-tags pedestal-context))}
      ;; Polling / one-shot mode (unchanged)
      (let [interval-ms (when (and fps (pos? fps))
                          (long (/ 1000.0 fps)))]
        {:name (keyword "ai.obney.grain.datastar.core" (str "stream-" (name query-name)))
         :enter #(stream-view-enter context query-name interval-ms heartbeat-delay %)}))))

;; --------------- ;;
;; Shim Page       ;;
;; --------------- ;;

(def ^:private default-datastar-url
  "https://cdn.jsdelivr.net/gh/starfederation/datastar@v1.0.0-RC.7/bundles/datastar.js")

(defn- shim-page-enter
  "Enter fn for shim-page interceptor."
  [opts context]
  (let [{:keys [title stream-path body head datastar-url html-attrs stream-method]
         :or {title "Grain App" datastar-url default-datastar-url stream-method "get"}} opts
        query-string (get-in context [:request :query-string])
        ;; Resolve path params (e.g. :event-id → actual UUID) in the stream URL
        path-params (get-in context [:request :path-params])
        resolved-stream-path (if (and stream-path (seq path-params))
                               (reduce-kv (fn [p k v]
                                            (string/replace p (str ":" (name k)) (str v)))
                                          stream-path path-params)
                               stream-path)
        ;; Generate a unique nonce per page load so each tab/navigation gets its own SSE.
        ;; Emitted as a signal so Datastar includes it in every request automatically.
        ;; Also appended to the stream URL as a query param for the initial connection.
        nonce (str (random-uuid))
        effective-stream-path (when resolved-stream-path
                                (let [base (if (and query-string (seq query-string))
                                             (str resolved-stream-path "?" query-string)
                                             resolved-stream-path)
                                      separator (if (string/includes? base "?") "&" "?")]
                                  (str base separator "dsNonce=" nonce)))
        page-html (str "<!DOCTYPE html>"
                       (h/html
                         [:html (or html-attrs {})
                          [:head
                           [:meta {:charset "UTF-8"}]
                           [:meta {:name "viewport" :content "width=device-width, initial-scale=1.0"}]
                           [:title title]
                           [:script {:type "module" :src datastar-url}]
                           (when head (if (fn? head) (head) head))]
                          [:body (cond-> {}
                                  effective-stream-path
                                  (assoc :data-init (str "@" stream-method "('" effective-stream-path "')"))
                                  ;; Nonce as signal so Datastar sends it with every @get and @post
                                  effective-stream-path
                                  (assoc :data-signals (str "{'dsNonce': '" nonce "'}")))


                           (when body body)
                           (when effective-stream-path
                             [:div {:id "app"}])]]))]
    (assoc context :response
           {:status 200
            :headers {"Content-Type" "text/html; charset=UTF-8"
                      "Cache-Control" "no-store"}
            :body page-html})))

(defn shim-page
  "Interceptor factory. HTML shell with Datastar JS.
   Forwards the request's query string to the stream-path URL so that
   query params (e.g. ?error=...) are available to the stream-view query."
  [opts]
  {:name ::shim-page
   :enter #(shim-page-enter opts %)})

;; ---------------------- ;;
;; Command Action Handler ;;
;; ---------------------- ;;

(defn execute-action
  "Executes a command from raw signals. Returns an SSE event map."
  [context signals]
  (let [command (decode-json-command signals)
        command-context (assoc context :command command)
        command-registry (or (:command-registry command-context)
                             @cp/command-registry*)
        authorized? (get-in command-registry
                           [(:command/name command) :authorized?])]
    (if (and authorized? (true? (authorized? command-context)))
      (let [result (cp/process-command command-context)]
        (cond
          (anomaly? result)
          (patch-signals (cond-> {:error (::anom/message result)}
                           (:error/explain result)
                           (assoc :fieldErrors (:error/explain result)))
                         {})

          (:datastar/signals result)
          (patch-signals (:datastar/signals result) {})

          (:command/result result)
          (patch-signals (:command/result result) {})))
      (do
        (when-not authorized?
          (u/log ::missing-authorized-predicate :command-name (:command/name command)))
        (patch-signals {:error "Unauthorized"} {})))))

(defn- action-handler-enter
  "Enter fn for action-handler interceptor."
  [context heartbeat-delay pedestal-context]
  (let [signals (parse-signals (:request pedestal-context))
        additional-context (:grain/additional-context pedestal-context)
        context-with-auth (merge context additional-context)]
    (sse/start-stream
      (fn [event-ch _sse-ctx]
        (try
          (when-let [event (execute-action context-with-auth signals)]
            (async/>!! event-ch event))
          (catch Exception e (u/log ::action-handler-error :error e))
          (finally (async/close! event-ch))))
      pedestal-context
      heartbeat-delay)))

(defn action-handler
  "Interceptor factory. Processes commands from Datastar signals."
  [context opts]
  (let [{:keys [heartbeat-delay] :or {heartbeat-delay 10}} opts]
    {:name ::action-handler
     :enter #(action-handler-enter context heartbeat-delay %)}))

;; ----------------------------- ;;
;; Auth-Redirect Interceptor     ;;
;; ----------------------------- ;;

(defn auth-redirect-interceptor
  "Interceptor factory. Checks authorization via the query's :authorized? predicate
   and redirects with 302 when the user is unauthenticated or unauthorized.

   opts:
     :authorized?      — predicate fn, receives {:auth-claims claims}
     :unauthenticated  — redirect path when no claims present (e.g. \"/auth/sign-in\")
     :unauthorized     — redirect path when claims present but predicate fails (e.g. \"/dashboard\")"
  [{:keys [authorized? unauthenticated unauthorized]}]
  {:name ::auth-redirect
   :enter
   (fn [ctx]
     (let [claims (get-in ctx [:grain/additional-context :auth-claims])]
       (cond
         (authorized? {:auth-claims claims}) ctx
         (not claims) (assoc ctx :response {:status 302 :headers {"Location" unauthenticated}})
         :else (assoc ctx :response {:status 302 :headers {"Location" unauthorized}}))))})

;; ---------------------- ;;
;; Gate Interceptor        ;;
;; ---------------------- ;;

(defn gate-interceptor
  "Interceptor factory. Calls check-fn with the grain context merged with
   per-request auth claims. Redirects with 302 on falsy result.

   context  — grain system context (event store, cache, etc.)
   gate-opts:
     :check    — (fn [context] boolean), receives grain context + auth claims
     :redirect — path to redirect to on failure"
  [context {:keys [check redirect]}]
  {:name ::gate
   :enter
   (fn [ctx]
     (let [additional (get ctx :grain/additional-context)
           gate-ctx (merge context additional)
           result (check gate-ctx)]
       (if result
         ctx
         (assoc ctx :response
                {:status 302
                 :headers {"Location" redirect}}))))})

;; ---------------------- ;;
;; Auto-Route Generation  ;;
;; ---------------------- ;;

(defn- query-name->route-name
  "Converts :user/sign-in-page to ::user-sign-in-page"
  [query-name]
  (keyword "ai.obney.grain.datastar.core"
           (str (namespace query-name) "-" (name query-name))))

(defn- query->route-pair
  "Given a query-name and its registry entry, returns [shim-route stream-route].
   Returns nil if the entry has no :datastar/path.
   defaults is an optional map with :datastar/shim-opts and :datastar/auth-redirect."
  [context query-name entry defaults]
  (when-let [path (:datastar/path entry)]
    (let [stream-path (if (= path "/") "/__stream" (str path "/__stream"))
          title (or (:datastar/title entry) "Grain App")
          fps (:datastar/fps entry 30)
          explicit-interceptors (or (:datastar/interceptors entry) [])
          ;; Auto-generate auth-redirect interceptor when configured in defaults
          ;; and the query's :authorized? predicate rejects empty context (non-public).
          auth-redirect-config (:datastar/auth-redirect defaults)
          authorized? (:authorized? entry)
          public? (and authorized? (try (authorized? {}) (catch Exception _ false)))
          auth-interceptor (when (and auth-redirect-config authorized? (not public?))
                             (auth-redirect-interceptor
                              (assoc auth-redirect-config :authorized? authorized?)))
          ;; Auto-generate gate interceptor when :datastar/gate is declared.
          ;; Gate redirect falls back to :unauthorized from auth-redirect defaults.
          gate-config (:datastar/gate entry)
          gate-int (when gate-config
                     (let [redirect (or (:redirect gate-config)
                                        (get-in defaults [:datastar/auth-redirect :unauthorized]))]
                       (gate-interceptor context (assoc gate-config :redirect redirect))))
          interceptors (cond-> []
                         auth-interceptor (conj auth-interceptor)
                         gate-int (conj gate-int)
                         true (into explicit-interceptors))
          shim-opts (merge {:title title :stream-path stream-path}
                           (:datastar/shim-opts defaults)
                           (:datastar/shim-opts entry))
          route-base (query-name->route-name query-name)
          read-models (:grain/read-models entry)
          event-types (when (seq read-models) (resolve-events read-models))
          debounce-ms (:datastar/debounce-ms entry 50)
          event-tags (:datastar/event-tags entry)
          stream-opts (cond-> {:fps fps}
                        (seq event-types) (assoc :event-types event-types
                                                 :debounce-ms debounce-ms)
                        event-tags (assoc :event-tags event-tags))]
      (let [with-signals (fn [extra]
                          (into [parse-datastar-signals] (concat interceptors extra)))]
        [;; Shim page route (GET)
         [path :get (with-signals [(shim-page shim-opts)])
          :route-name (keyword (namespace route-base)
                               (str (name route-base) "-page"))]
         ;; Stream route (GET — initial page load via @get)
         [stream-path :get (with-signals [(stream-view context query-name stream-opts)])
          :route-name (keyword (namespace route-base)
                               (str (name route-base) "-stream"))]
         ;; Stream route (POST — @post sends signals in body)
         [stream-path :post (with-signals [(stream-view context query-name stream-opts)])
          :route-name (keyword (namespace route-base)
                               (str (name route-base) "-stream-post"))]]))))

(defn routes
  "Scans the query registry for entries with :datastar/path and generates
   Pedestal route pairs (shim-page + stream-view) for each.

   Optional overrides map: {query-name {:datastar/fps 2 :datastar/interceptors [...]}}
   Optional defaults map: {:datastar/shim-opts {:head fn :html-attrs {} :datastar-url str}}
     Defaults are applied to all routes; per-query shim-opts override them."
  ([context] (routes context {} {}))
  ([context overrides] (routes context overrides {}))
  ([context overrides defaults]
   (let [registry (or (:query-registry context) @qp/query-registry*)]
     (into #{}
           (comp
            (filter (fn [[_ entry]] (:datastar/path entry)))
            (mapcat (fn [[qname entry]]
                      (let [merged (merge entry (get overrides qname))]
                        (query->route-pair context qname merged defaults))))
            (remove nil?))
           registry))))
