(ns ai.obney.grain.datastar.interface
  "Public API for Grain's Datastar integration.

   Most consumers only need `routes` (auto-generates shim + stream routes from
   query metadata, with optional auth-redirect and gate interceptors) and
   `action-handler` (processes commands from Datastar @post).
   The lower-level functions (`stream-view`, `shim-page`, `patch-elements`,
   `patch-signals`, `auth-redirect-interceptor`, `gate-interceptor`) are
   available for custom route wiring.

   See `ai.obney.grain.datastar.core` namespace docstring for architecture overview."
  (:require [ai.obney.grain.datastar.core :as core]))

(defn stream-view
  "Interceptor factory. Opens an SSE that streams `:datastar/hiccup` from a query.

   Three modes, selected automatically:
   - **Event-driven**: when `:event-types` is non-empty AND `:event-pubsub` is in
     context — re-renders only when relevant domain events fire. POST requests
     update the existing SSE's signals without opening a new connection.
   - **Polling**: when `:fps` > 0 — re-renders on a timer.
   - **One-shot**: when `:fps` is 0 or nil — renders once and closes.

   opts keys:
     :fps            — frames per second for polling mode (default 30, ignored in event-driven)
     :heartbeat-delay — SSE heartbeat interval in seconds (default 10)
     :event-types    — set of event type keywords to subscribe to
     :debounce-ms    — ms to wait before re-rendering after an event (default 50)
     :event-tags     — map of {:tag-key :query-key} for tag-based event filtering"
  [context query-name opts]
  (core/stream-view context query-name opts))

(defn shim-page
  "Interceptor factory. Returns an HTML shell that boots Datastar JS and opens
   an SSE connection to `stream-path` via `@get` (or `@post`).

   Generates a unique nonce per page load so multiple tabs get independent SSE
   streams. The nonce is emitted as a Datastar signal so it's included in every
   request automatically, and appended to the stream URL as a query param.

   Path parameters in `:stream-path` (e.g., `:item-id` in `\"/items/:item-id/__stream\"`)
   are automatically resolved from the request's `:path-params` map.

   opts keys:
     :title         — HTML <title> (default \"Grain App\")
     :stream-path   — SSE endpoint path (e.g., \"/my-page/__stream\")
     :stream-method — \"get\" (default) or \"post\"
     :head          — extra <head> hiccup or (fn [] hiccup)
     :body          — extra <body> hiccup (rendered before the #app div)
     :html-attrs    — attributes for the <html> element
     :datastar-url  — CDN URL for Datastar JS (default RC.7)"
  [opts]
  (core/shim-page opts))

(defn action-handler
  "Interceptor factory. Parses a command from Datastar signals (POST body),
   executes it via the command processor, and returns the result as an SSE event.

   On success: sends `datastar-patch-signals` with `:datastar/signals` from the
   command result (e.g., `{:__toast \"Saved\"}`).
   On failure: sends `datastar-patch-signals` with `:error` and optional `:fieldErrors`.
   On unauthorized: sends `datastar-patch-signals` with `{:error \"Unauthorized\"}`."
  [context opts]
  (core/action-handler context opts))

(defn render-html
  "Render a hiccup data structure to an HTML string."
  [hiccup]
  (core/render-html hiccup))

(defn patch-elements
  "Build a `datastar-patch-elements` SSE event map from an HTML string.

   opts keys:
     :selector — CSS selector to patch (default: Datastar's default, usually #app)
     :mode     — :inner (default) or :outer (replaces the element itself)"
  [html opts]
  (core/patch-elements html opts))

(defn patch-signals
  "Build a `datastar-patch-signals` SSE event map from a signal map.

   opts keys:
     :only-if-missing — when true, only sets signals that don't already exist on the client"
  [signals opts]
  (core/patch-signals signals opts))

(defn auth-redirect-interceptor
  "Interceptor factory. Checks authorization and redirects with 302 when the
   user is unauthenticated or unauthorized. Reads auth claims from
   `[:grain/additional-context :auth-claims]`.

   Auto-generated by `routes` when `:datastar/auth-redirect` is in the defaults
   map. Available here for consumers who need it on manually-wired routes.

   opts:
     :authorized?      — predicate fn, receives {:auth-claims claims}
     :unauthenticated  — redirect path when no claims (e.g. \"/auth/sign-in\")
     :unauthorized     — redirect path when unauthorized (e.g. \"/dashboard\")"
  [opts]
  (core/auth-redirect-interceptor opts))

(defn gate-interceptor
  "Interceptor factory. Calls a check function with the grain context merged
   with per-request auth claims. Redirects with 302 on falsy result.

   Auto-generated by `routes` when a query declares `:datastar/gate`.
   Available here for consumers who need it on manually-wired routes.

   context   — grain system context (event store, cache, etc.)
   gate-opts:
     :check    — (fn [context] boolean)
     :redirect — path to redirect to on failure"
  [context gate-opts]
  (core/gate-interceptor context gate-opts))

(def parse-datastar-signals
  "Interceptor that extracts Datastar signals from the request and merges them
   into `:query-params`. Handles both GET (`?datastar={...}` query param) and
   POST (JSON body, wrapped or flat). Auto-included by `routes` on all generated
   routes — only needed when wiring routes manually."
  core/parse-datastar-signals)

(defn routes
  "Scan the query registry for entries with `:datastar/path` metadata and generate
   Pedestal routes. Each query produces three routes:

     1. GET  `/path`           — Shim page (HTML shell that boots Datastar)
     2. GET  `/path/__stream` — SSE connection (reuses existing session if nonce matches)
     3. POST `/path/__stream` — Signal updates on existing SSE (Datastar's `@post`)

   Optional `overrides` map merges additional metadata per query-name, e.g.:
     {::my-query {:datastar/fps 2 :datastar/interceptors [auth-interceptor]}}

   Optional `defaults` map applies to all generated routes:
     {:datastar/shim-opts {:head (fn [] hiccup)    ;; default <head> content
                           :html-attrs {:lang \"en\"} ;; default <html> attributes
                           :datastar-url \"...\"}}    ;; override Datastar CDN URL
      :datastar/auth-redirect {:unauthenticated \"/sign-in\"  ;; 302 when no claims
                                :unauthorized \"/dashboard\"}} ;; 302 when role mismatch
   Per-query `:datastar/shim-opts` (from registry or overrides) take precedence.
   Auth-redirect interceptors are auto-generated from each query's `:authorized?`
   predicate. Public queries (where `(authorized? {})` returns truthy) are skipped.

   Queries may also declare `:datastar/gate {:check fn :redirect path}` for
   context-dependent guards (e.g., shift-ready checks). The adapter builds the
   interceptor at route time, passing the grain context to `:check` at request time.
   If `:redirect` is omitted, falls back to `:unauthorized` from auth-redirect defaults."
  ([context] (core/routes context))
  ([context overrides] (core/routes context overrides))
  ([context overrides defaults] (core/routes context overrides defaults)))
